# Generated by Django 5.1.4 on 2024-12-30 22:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MouseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Ник пользователя')),
                ('user_id', models.PositiveBigIntegerField(unique=True, verbose_name='User ID')),
                ('count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Монеты')),
                ('factor', models.PositiveIntegerField(default=1, verbose_name='Множитель')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('language_code', models.CharField(default='ru', max_length=8, verbose_name='Код языка')),
                ('is_premium', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('point', models.PositiveIntegerField()),
                ('times', models.PositiveIntegerField(default=1)),
                ('url', models.URLField(blank=True, default='')),
                ('label', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, default='condition/default.png', null=True, upload_to='condition/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='game.mouseuser')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['condition', 'point', 'picture'],
            },
        ),
    ]
