# Generated by Django 5.1.4 on 2024-12-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_clickcounter_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
                ('point', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to='static/media/condition/')),
            ],
        ),
        migrations.RenameField(
            model_name='clickcounter',
            old_name='multiplier',
            new_name='factor',
        ),
    ]
