# Generated by Django 5.1.4 on 2024-12-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_condition_rename_multiplier_clickcounter_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='picture',
            field=models.ImageField(upload_to='media/condition/'),
        ),
    ]
