# Generated by Django 5.1.4 on 2024-12-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_condition_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='picture',
            field=models.ImageField(default='condition/default.png', upload_to='condition/'),
        ),
    ]
