# Generated by Django 5.1.4 on 2024-12-24 17:23

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('game', '0008_alter_condition_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='picture',
            field=models.ImageField(blank=True, default='condition/default.png', null=True, upload_to='condition/'),
        ),
        migrations.CreateModel(
            name='MouseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(default='-_-', max_length=100, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Ник пользователя')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='User ID')),
                ('count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Монеты')),
                ('factor', models.PositiveIntegerField(default=1, verbose_name='Множитель')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('language_code', models.CharField(default='ru', max_length=8, verbose_name='Код языка')),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
