# Generated by Django 5.1.4 on 2024-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_condition_picture_mouseuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mouseuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='mouseuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='mouseuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mouseuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mouseuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mouseuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='mouseuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='mouseuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mouseuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='mouseuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
