# Generated by Django 5.1.4 on 2024-12-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_mouseuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouseuser',
            name='password',
        ),
        migrations.AddField(
            model_name='mouseuser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mouseuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='mouseuser',
            name='user_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='User ID'),
        ),
    ]
