# Generated by Django 5.1.4 on 2024-12-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_mouseuser_password_mouseuser_is_premium_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Condition',
            new_name='Tasks',
        ),
        migrations.DeleteModel(
            name='ClickCounter',
        ),
    ]
