# Generated by Django 5.1.4 on 2024-12-24 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_rename_condition_tasks_delete_clickcounter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['condition', 'point', 'picture'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
    ]
